; These commands are the saved state of coot.  You can evaluate them
; using "Calculate->Run Script...".
;;molecule-info: dna-coot-3.pdb
(set-graphics-window-size 1529 767)
(set-graphics-window-position 0 0)
(set-model-fit-refine-dialog-position 1246 147)
(vt-surface 2)
(set-clipping-front  0.00)
(set-clipping-back  0.00)
(set-map-radius 10.00)
(set-iso-level-increment  0.0500)
(set-diff-map-iso-level-increment  0.0050)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-flag 1)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-swap-difference-map-colours 0)
(set-background-colour  0.00  0.00  0.00)
(set-symmetry-size 13.00)
(set-symmetry-colour-merge  0.50)
(set-symmetry-colour  0.10  0.20  0.80)
(set-symmetry-atom-labels-expanded 0)
(set-active-map-drag-flag 1)
(set-show-aniso 0)
(set-aniso-probability 50.00)
(set-smooth-scroll-steps 40)
(set-smooth-scroll-limit 10.00)
(set-font-size 2)
(set-rotation-centre-size  0.10)
(set-do-anti-aliasing 0)
(set-default-bond-thickness 5)
(handle-read-draw-molecule "/home/german/labo/17/facu/muts_mp_1jgg/1/dna-coot-3.pdb")
(set-molecule-bonds-colour-map-rotation 0 21.00)
(set-draw-hydrogens 0 1)
(set-matrix 60.00)
(set-show-symmetry-master 0)
(set-go-to-atom-molecule 0)
(set-go-to-atom-chain-residue-atom-name "B" 15 " P  ")
(scale-zoom  1.00)
(set-rotation-centre 20.42 20.55 31.73)
(set-view-quaternion -0.9718 -0.0015  0.0857  0.2195)
(post-model-fit-refine-dialog)
