
>P1;1jgg
structureX:1jgg.pdb:   1 :@:+122 ::::-1.00:-1.00
........./.........../TRDQLGRLEKEFYKENYVSRPRRCELAAQLNLPESTIKVWFQNRRMKDKRQ/T
RDQLGRLEKEFYKENYVSRPRRCELAAQLNLPESTIKVWFQNRRMKDKRQ*

>P1;mp
sequence:mp:     : :     : :::-1.00:-1.00
........./.........../TTDQVKSLEKNFELENKLEPERKLQLARELGLQPRQVAVWFQNRRARWKTK/T
TDQVKSLEKNFELENKLEPERKLQLARELGLQPRQVAVWFQNRRARWKTK*
