>P1;1jgg
structureX:1jgg.pdb :1:@:+134 ::::-1.00:-1.00
....................RYRTAFTRDQLGRLEKEFYKENYVSRPRRCELAAQLNLPESTIKVWFQNRRMKDK
RQ----------/RYRTAFTRDQLGRLEKEFYKENYVSRPRRCELAAQLNLPESTIKVWFQNRRMKDKRQ-----
-----*

>P1;mp
sequence:mp:     : :     : :::-1.00:-1.00
....................--KRRLTTDQVKSLEKNFELENKLEPERKLQLARELGLQPRQVAVWFQNRRARWK
TKQLERDYDVLK/--KRRLTTDQVKSLEKNFELENKLEPERKLQLARELGLQPRQVAVWFQNRRARWKTKQLERD
YDVLK*
