(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening None, Welcome to Coot. 0.7.2 (revision 4730)  [with guile 1.8.8 embedded] [with python 2.7.5 embedded]")
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening german,,,. Welcome to Coot")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "1jgg.pdb" 1)
(use-graphics-interface-state)
(coot-checked-exit 0)
(clear-backups-maybe)
(stereo-mode-state)
(stereo-mode-state)
(save-state)
