filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening None, Welcome to Coot. 0.7.2 (revision 4730)  [with guile 1.8.8 embedded] [with python 2.7.5 embedded]")
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening german,,,. Welcome to Coot")
set_display_lists_for_maps (0)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
handle_read_draw_molecule_with_recentre ("1jgg.pdb", 1)
use_graphics_interface_state ()
coot_checked_exit (0)
;; # DIRECT SCHEME ((clear-backups-maybe))
stereo_mode_state ()
stereo_mode_state ()
save_state ()
